version: "3"

services:
  mysqldb:
    image: mysql
    restart: always
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: music-for-play
    ports:
      - '3307:3306'
    volumes:
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data


  # Node services
  nest-js:
    container_name: nest-js #optional
    build:
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - mysqldb
    working_dir: /app


volumes:
  db-config:
  db-data:

